# .appveyor.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

# This is YAML - indentation levels are crucial

cache:
  - C:\Users\appveyor\.tools

init:
  - git config --global core.autocrlf true

clone_depth: 50

skip_commits:
  files:
    - 'documentation/*'
    - 'templates/*'
    - '**/*.html'
    - '**/*.md'
    - '.travis.yml'

image: Visual Studio 2019

# Build Configurations: dll/static, regular/debug
configuration:
  - dynamic
  - static

environment:
  # common / default variables for all jobs
  SETUP_PATH: .ci-local:.ci

  matrix:
  - CMP: vs2019
    BASE: 7.0
  - CMP: vs2019
    BASE: 3.15

# Platform: processor architecture
platform:
  - x64

install:
  - cmd: git submodule update --init --recursive
  - cmd: python .ci/appveyor/do.py prepare

build_script:
  - cmd: python .ci/appveyor/do.py build

test_script:
  - cmd: python .ci/appveyor/do.py test

on_finish:
  - ps: Get-ChildItem *.tap -Recurse -Force | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - cmd: python .ci/appveyor/do.py build test-results -s

notifications:
  - provider: GitHubPullRequest
